replicaCount: 1

image:
  repository: 447182646004.dkr.ecr.us-east-1.amazonaws.com/basic-app
  tag: 4ee1247f7a545b391dac7053ce50559aa9f4052c

ingress:
  host: dev.myapp.local
  albName: dev-alb

autoscaling:
  minReplicas: 1
  maxReplicas: 2
