replicaCount: 1

image:
  repository: 447182646004.dkr.ecr.us-east-1.amazonaws.com/basic-app
  tag: cf2923f89bd7745edd7875693847a9ca5f095a57

ingress:
  host: dev.myapp.local
  albName: dev-alb

autoscaling:
  minReplicas: 1
  maxReplicas: 2
