replicaCount: 3

image:
  repository: 447182646004.dkr.ecr.us-east-1.amazonaws.com/basic-app
  tag: cf2923f89bd7745edd7875693847a9ca5f095a57

ingress:
  host: prod.myapp.local
  albName: prod-alb

autoscaling:
  minReplicas: 3
  maxReplicas: 6
